sudo: required
dist: trusty
language: python
cache: pip
matrix:
    include:
        - python: 2.7
        # - python: 3.4
        # - python: 3.5
        - python: 3.6
before_install:
  - sudo apt-get update
  # apparently, Trusty from GCP sticks some gunk inside here to smooth out 
  # stuff with GCP & boto. This is a bit useless in CI. See this issue for 
  # more details: https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg
install:
  - mkdir ~/.aws && printf "[default]\noutput = json\nregion = us-west-2" > ~/.aws/config
  - export BASE_DIR=$(pwd)
  - echo $(python --version)
  - pip install -e .[aws,tests]
  - cd $BASE_DIR
  
# command to run tests
script:
  - PYTHONPATH=$(pwd) py.test --pep8 -m pep8
  - PYTHONPATH=$(pwd) py.test test/
after_success:
  - coveralls