sudo: required
dist: trusty
language: python
cache: pip
matrix:
    include:
        - python: 2.7
          env: MODE=unit
        - python: 3.6
          env: MODE=unit
        - python: 3.6
          env: MODE=pep8
before_install:
  - sudo apt-get update
  # apparently, Trusty from GCP sticks some gunk inside here to smooth out 
  # stuff with GCP & boto. This is a bit useless in CI. See this issue for 
  # more details: https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg
install:
  - mkdir ~/.aws && printf "[default]\noutput = json\nregion = us-west-2" > ~/.aws/config
  - export BASE_DIR=$(pwd)
  - echo $(python --version)
  - pip install -e .[aws,tests]
  - cd $BASE_DIR
  
# command to run tests
script:
  - if [[ "$MODE" == "pep8" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8 ;
    else
      PYTHONPATH=$PWD:$PYTHONPATH py.test test/ ;
    fi
after_success:
  - coveralls