sudo: required
dist: trusty
language: python
cache: pip
matrix:
    include:
        - python: 2.7
        # - python: 3.4
        # - python: 3.5
        # - python: 3.6
before_install:
  - sudo apt-get update
install:
  - mkdir ~/.aws && printf "[default]\noutput = json\nregion = us-west-2" > ~/.aws/config
  - export BASE_DIR=$(pwd)
  - echo $(python --version)
  - pip install -e .[aws,tests]
  - cd $BASE_DIR
# command to run tests
script:
  - PYTHONPATH=$(pwd) py.test --pep8 -m pep8
  - PYTHONPATH=$(pwd) py.test test/
after_success:
  - coveralls